language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 7.0

before_install:
  - sudo apt-get update > /dev/null
<<<<<<< Updated upstream

install:
  # install Oracle JDK8
  - sh -c ./CI/jdk8-install.sh
  # install gremlin-server
  - sh -c ./CI/gremlin-server/install.sh
  # install neo4j
  - sh -c ./CI/neo4j/install.sh
  # install orient
  - sh -c ./CI/orient/install.sh
=======
  - chmod -R +x ./CI

install:
  - sh -c ./CI/travis-setup.sh
>>>>>>> Stashed changes

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

